/*
 * Plugin that provides API-first development using OpenAPI-generator to
 * generate Spring-MVC endpoint stubs at compile time from an OpenAPI definition file
 */
buildscript {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    dependencies {
        classpath "org.openapitools:openapi-generator-gradle-plugin:${openapiPluginVersion}"
    }
}
apply plugin: "org.openapi.generator"

import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

// generator 7 with the Boot 3+/Jakarta templates
Map<String, String> commonConfigOptions = [delegatePattern: "true", title: "hub", useSpringBoot3: "true",
                                           useJakartaEe: "true"]

tasks.register("openApiGenerateV2", GenerateTask) {
    generatorName = "spring"
    inputSpec = "$rootDir/src/main/resources/swagger/api.yml".toString()
    outputDir = layout.buildDirectory.dir("openapi").get().asFile.toString()
    apiPackage = "com.icthh.xm.tmf.ms.prepaybalance.web.v2.api"
    modelPackage = "com.icthh.xm.tmf.ms.prepaybalance.web.v2.api.model"
    apiFilesConstrainedTo = [""]
    modelFilesConstrainedTo = [""]
    supportingFilesConstrainedTo = ["ApiUtil.java"]
    configOptions = commonConfigOptions
    validateSpec = true
    importMappings = [Problem: "org.zalando.problem.Problem"]
}

tasks.register("openApiGenerateV4", GenerateTask) {
    generatorName = "spring"
    inputSpec = "$rootDir/src/main/resources/swagger/apiv4.yml".toString()
    outputDir = layout.buildDirectory.dir("openapi").get().asFile.toString()
    apiPackage = "com.icthh.xm.tmf.ms.prepaybalance.web.v4.api"
    modelPackage = "com.icthh.xm.tmf.ms.prepaybalance.web.v4.api.model"
    apiFilesConstrainedTo = [""]
    modelFilesConstrainedTo = [""]
    supportingFilesConstrainedTo = ["ApiUtil.java"]
    configOptions = commonConfigOptions
    validateSpec = true
    importMappings = [Problem: "org.zalando.problem.Problem"]
    additionalProperties = [useTags: "true"]
}

sourceSets {
    main {
        java {
            srcDir file(layout.buildDirectory.dir("openapi/src/main/java").get().asFile)
        }
    }
}

compileJava.dependsOn("openApiGenerateV2", "openApiGenerateV4")
